### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Briles** [FichteFoll/SublimeLinter-contrib-sublime-syntax#1]
On Windows 10 with ST v3109 I get a `Unicode Encode Error` when linting the CSS syntax test from sublimehq/Packages

Seems the tempfile's contents aren't being written as UTF8

Stack trace:

```
Traceback (most recent call last):
  File "C:\Sublime Syntax Test\Data\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "C:\Sublime Syntax Test\Data\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "C:\Sublime Syntax Test\Data\Packages\SublimeLinter\sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Sublime Syntax Test\Data\Packages\SublimeLinter\lint\linter.py", line 929, in lint_view
    linter.lint(hit_time)
  File "C:\Sublime Syntax Test\Data\Packages\SublimeLinter\lint\linter.py", line 1397, in lint
    output = self.run(cmd, self.code)
  File "linter in C:\Sublime Syntax Test\Data\Installed Packages\SublimeLinter-contrib-sublime-syntax.sublime-package", line 66, in run
  File "./python3.3/contextlib.py", line 48, in __enter__
  File "linter in C:\Sublime Syntax Test\Data\Installed Packages\SublimeLinter-contrib-sublime-syntax.sublime-package", line 137, in _temporary_resource_file
  File "./python3.3/encodings/cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f600' in position 22375: character maps to <undefined>
```

**Comment by FichteFoll** [comment]
Ah, good catch (and easy fix). Thanks for the report.
